dist: trusty
language: php

php:
  - 7.2
  - 7.4

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

## Commented out until version 1.0 (version 0.1.. doesn't follow semver)
# matrix:
#   include:
#     - php: 7.3
#       env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
    # For PHP 7.2 replace PHP version constraint from 7.4 to 7.2
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then composer require php:~7.2 --no-update --no-scripts; fi
    # For PHP 7.2 remove PHPUnit: version cannot be satisfied, and tests are not run anyway
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then composer remove phpunit/phpunit --dev --no-update --no-scripts; fi
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
    # Use Rector to downgrade code from PHP 7.4 to 7.2
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then vendor/bin/rector process src; fi

script:
  # Tests only on PHP 7.4
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.2" ]]; then vendor/bin/phpcs -n --standard=psr2 src/; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.2" ]]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi
  # Code analysis on all PHP versions
  - vendor/bin/phpstan analyse -c phpstan.neon.dist src

after_script:
  # Tests only on PHP 7.4
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.2" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

notifications:
  email:
    recipients:
      - leo@getpop.org
    on_success: change
    on_failure: always
