dist: trusty
language: php

php:
  - 7.1
  - 7.4

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

## Commented out until version 1.0 (version 0.1.. doesn't follow semver)
# matrix:
#   include:
#     - php: 7.3
#       env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then sed -i 's/"php": "~7.4"/"php": "~7.1"/' composer.json; fi
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then vendor/bin/rector process src; fi

script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]]; then vendor/bin/phpcs -n --standard=psr2 src/; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi
  - vendor/bin/phpstan analyse -c phpstan.neon.dist src

after_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

notifications:
  email:
    recipients:
      - leo@getpop.org
    on_success: change
    on_failure: always
